- e_metrobus/static/sass/_footer.scss
- e_metrobus/static/sass/_layout.scss
- e_metrobus/static/sass/_top-bar.scss
- e_metrobus/static/sass/app.scss
- e_metrobus/templates/base.html
- e_metrobus/templates/navigation/route.html
- e_metrobus/templates/navigation/start.html
> Base template for project

- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_dashboard.scss
- e_metrobus/static/sass/app.scss
- e_metrobus/templates/navigation/dashboard.html
> Popup is only shown, if user visits dashboard for the first time

- e_metrobus/static/images/icons/i_star_black.svg
- e_metrobus/static/images/icons/i_star_turkis.svg
- e_metrobus/static/libs/foundation-sites/scss/components/_button.scss
- e_metrobus/static/sass/_animate_answer.scss
- e_metrobus/static/sass/_components.scss
- e_metrobus/static/sass/_landing_page.scss
- e_metrobus/static/sass/_route.scss
- e_metrobus/static/sass/_settings.scss
- e_metrobus/templates/navigation/answer.html
- e_metrobus/templates/widgets/stations.html
Added star/points animation when user gets right answer. False answer stays the same
Issue #52
> Right answer points

- CHANGELOG.md
- e_metrobus/navigation/urls.py
- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_category_finished.scss
- e_metrobus/static/sass/app.scss
- e_metrobus/templates/navigation/category_finished.html
> Show "category finished" page

- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_animate_answer.scss
- e_metrobus/templates/navigation/answer.html
Issue #52 
Score is taken from backend
Todo:
> Correct (dynamic) score points are showed in template

- CHANGELOG.md
- e_metrobus/navigation/views.py
> Footer links

- e_metrobus/templates/navigation/question.html
Radio button click triggers submit after 300ms
Closes #104 
Closes #95
> Removed answer button on question page

- e_metrobus/static/sass/_landing_page.scss
- e_metrobus/templates/navigation/landing_page.html
The text and buttons are now centered and the logos at the bottom of the page
fix #113
> Reduce logos

- compose/local/django/Dockerfile
- e_metrobus/static/libs/foundation-sites/scss/components/_accordion.scss
- e_metrobus/static/sass/_dashboard.scss
- e_metrobus/static/sass/_questions_as_text.scss
- e_metrobus/templates/navigation/questions_as_text.html
- requirements/base.txt
> Popup close

- compose/local/django/Dockerfile
- e_metrobus/static/libs/foundation-sites/scss/components/_accordion.scss
- e_metrobus/static/sass/_questions_as_text.scss
- e_metrobus/templates/navigation/answer.html
- e_metrobus/templates/navigation/category_finished.html
- e_metrobus/templates/navigation/questions_as_text.html
- requirements/base.txt
Now the user can tap on the screen after answering the question to skip the animation
> Answer animation

- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_question.scss
- e_metrobus/templates/navigation/question.html
> Added design for quiz progress bar

- CHANGELOG.md
- e_metrobus/static/js/stations.js
Closes #127 
Departure station can be changed after arrival station has been selected.
> Departure station can be changed

- e_metrobus/navigation/stations.csv
- e_metrobus/navigation/stations.py
- e_metrobus/navigation/views.py
- e_metrobus/templates/navigation/display_route.html
> Added real station data

- CHANGELOG.md
- e_metrobus/static/js/stations.js
> Third station clears selection

- CHANGELOG.md
- e_metrobus/navigation/views.py
- e_metrobus/templates/navigation/landing_page.html
> Skipping language skips fade-in on landing page

- e_metrobus/static/sass/_comparison.scss
@henhuy can you check if that works? maybe that was easier to fix than expected
fix #162
> remove black bg-color from close button

- e_metrobus/static/sass/_route.scss
- e_metrobus/templates/widgets/stations.html
> fix hidden stations bug

- e_metrobus/static/sass/_dashboard.scss
> Removed height and width of first question popup to fix jumping at hover

- e_metrobus/static/sass/_landing_page.scss
- e_metrobus/templates/includes/desktop.html
@henhuy can you update the language switch to make it work? I just copied the content from the mobile landing page and place it at the top of the desktop page
fix #147
> add switch language btn to desktop page

- CHANGELOG.md
- e_metrobus/navigation/questions.cfg
- e_metrobus/navigation/views.py
> First question answered after display_route

- e_metrobus/static/js/confetti.js
- e_metrobus/templates/navigation/quiz_finished.html
I just did minor changes to the confetti colors and the copy on the congratulations page
Fix #170
> changed confetti color and updated wording

- e_metrobus/templates/widgets/top_bar.html
The top-navigation star color has been set to blue
fix #171
> changed top-nav star color to blue

- CHANGELOG.md
- e_metrobus/navigation/chart.py
- package.json
> Remove chart zoom

- CHANGELOG.md
- e_metrobus/templates/navigation/questions_as_text.html
> Fixed question as text page

- CHANGELOG.md
- e_metrobus/navigation/views.py
> Fixed nan warning on environment page

- e_metrobus/static/images/Icon_E_Bus_BVG_error.svg
- e_metrobus/static/sass/_components.scss
- e_metrobus/static/sass/_route.scss
- e_metrobus/static/sass/_variables.scss
- e_metrobus/templates/navigation/route_dropdown.html
> Added reveal instead of alert to route dropdown page

- CHANGELOG.md
- e_metrobus/navigation/urls.py
- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_route.scss
> Enabled route dropdown as default

- compose/local/django/start
- compose/production/django/Dockerfile
- compose/production/django/start
> Massagecompile

- e_metrobus/navigation/urls.py
- e_metrobus/navigation/views.py
- e_metrobus/templates/navigation/finished_base.html
- e_metrobus/templates/navigation/quiz_finished.html
> Separated finished and share score page

- e_metrobus/navigation/views.py
> Once feedback page is visited, finished page does not redirect

- e_metrobus/static/sass/_category_finished.scss
> reduce category_finished icons height

- e_metrobus/static/sass/_feedback.scss
> center skip btn

- e_metrobus/static/images/Route_top_img_v2.svg
- e_metrobus/static/sass/_route.scss
Updated image on route page
fix #230
> update route image

- e_metrobus/static/sass/_top-bar.scss
- e_metrobus/templates/widgets/top_bar_route.html
> reduce back to route link width

- e_metrobus/static/sass/_comparison.scss
> add transparent bc-color to see data btn

- CHANGELOG.md
- e_metrobus/navigation/urls.py
- e_metrobus/navigation/views.py
- e_metrobus/templates/navigation/answer.html
- e_metrobus/templates/navigation/answer_score.html
- e_metrobus/templates/navigation/question.html
Fixes #235 
Split answer into two separated views (one for animation, other for answer text)
> Split answer view

- CHANGELOG.md
- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_display_route.scss
- e_metrobus/templates/navigation/display_route.html
> Added CO2 in gram on display route page

- e_metrobus/static/sass/_landing_page.scss
> shorten LP animation time

- e_metrobus/templates/navigation/landing_page.html
> add links to logos on mobile LP

- e_metrobus/templates/navigation/display_route.html
> increase distance km font-size

- CHANGELOG.md
- e_metrobus/navigation/constants.py
- e_metrobus/navigation/questions.py
- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_question.scss
- e_metrobus/templates/navigation/dashboard.html
- e_metrobus/templates/navigation/question.html
> Redesign progress circle

- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_feedback.scss
Closes #238 
Removed navigation from feedback page.
Maybe page design needs some polishing, @bmlancien ?
> Removed navigation from feedback page

- CHANGELOG.md
- e_metrobus/static/sass/_questions_as_text.scss
- e_metrobus/templates/navigation/questions_as_text.html
> Implemented logic for tabs on question-as-text-page

- CHANGELOG.md
- e_metrobus/navigation/widgets.py
- e_metrobus/static/images/icons/i_share.svg
- e_metrobus/static/sass/_quiz_finished.scss
- e_metrobus/static/sass/_top-bar.scss
- e_metrobus/templates/base.html
- e_metrobus/templates/widgets/top_bar.html
Closes #278 
Added logic for sharing in navigation bar.
> Implemented share button next to score

- e_metrobus/static/sass/_display_route.scss
> increase station names font sizes

- e_metrobus/static/sass/_components.scss
> align legal tabs correctly

- e_metrobus/static/sass/_category_finished.scss
- e_metrobus/templates/navigation/category_finished.html
> style and animate categorry_finished page

- e_metrobus/static/sass/_landing_page.scss
- e_metrobus/templates/includes/landscape.html
No big changes, just updated a few things.
fix #331
> make small changes on landscape view design

- e_metrobus/static/sass/_question.scss
- e_metrobus/templates/navigation/answer.html
> center answer box on tablet screens

- e_metrobus/static/sass/_category_finished.scss
> reverse animation

- e_metrobus/navigation/constants.py
- e_metrobus/templates/widgets/info_table.html
> Removed fuel/diesel from input and info table

- e_metrobus/static/sass/_question.scss
- e_metrobus/templates/navigation/question.html
@henhuy Use the `question__multiple-choice` class for multiple-choice layouts.
fix #359
> add multiple-choice class to target

- CHANGELOG.md
- e_metrobus/navigation/urls.py
- e_metrobus/navigation/utils.py
- e_metrobus/navigation/views.py
- e_metrobus/navigation/widgets.py
- e_metrobus/templates/navigation/quiz_finished.html
- e_metrobus/templates/widgets/top_bar.html
> Changed link and text for sharing

- e_metrobus/navigation/views.py
- e_metrobus/templates/questions/e_metrobus/batteries.html
- e_metrobus/templates/questions/politics/neutral.html
> Fixed wrong/missing image sources

- e_metrobus/templates/navigation/display_route.html
@henhuy I simply added "on my route" to the existing texts. I have tried with mockups to add "My route" at the top but I'm not really convinced...
fix #373
> add wording on your route

- e_metrobus/navigation/chart.py
- e_metrobus/navigation/utils.py
> Changed thousands and decimal separators for charts

- e_metrobus/navigation/chart.py
> Moved title to fix chart alignment

- CHANGELOG.md
- e_metrobus/navigation/views.py
- e_metrobus/templates/navigation/environment.html
> Changing route returns to environment page

- e_metrobus/static/sass/_landing_page.scss
- e_metrobus/static/sass/_legal.scss
- e_metrobus/templates/navigation/landing_page.html
- e_metrobus/templates/navigation/legal.html
> add logos to legal page

- config/settings/base.py
- config/settings/production.py
- e_metrobus/navigation/utils.py
- e_metrobus/navigation/views.py
- requirements/base.txt
- requirements/production.txt
> Feedback mails

- config/settings/base.py
- config/settings/production.py
- e_metrobus/navigation/utils.py
- e_metrobus/navigation/views.py
- requirements/base.txt
- requirements/production.txt
> Send bug report

- CHANGELOG.md
- e_metrobus/navigation/forms.py
- e_metrobus/templates/base.html
- e_metrobus/templates/widgets/feedback_comment.html
> Workaround for soft keyboard activating landscape view

- e_metrobus/static/sass/_landing_page.scss
- e_metrobus/templates/navigation/landing_page.html
@henhuy can you remember what the text was? I can't find it
fix #261
> add dummy text to mobile LP

- e_metrobus/templates/base.html
- e_metrobus/templates/includes/landscape.html
> Implemented mobile check to switch between desktop and mobile app

- e_metrobus/static/sass/_landing_page.scss
> center text and add animation to it

- e_metrobus/static/sass/_legal.scss
- e_metrobus/templates/navigation/legal.html
> reduce logos size

- e_metrobus/navigation/chart.py
- e_metrobus/static/sass/_display_route.scss
- e_metrobus/static/sass/_environment.scss
> change chart size for landscape

- locale/en/LC_MESSAGES/django.po
Hi @bmlancien,
I did a little change in my fork of the project.
You can see that it is a fork by branch name `henhuy:translation` (where henhuy is my private github account),
Now its your turn to merge PRs ;)
> Test Fork-PR for translation

- CHANGELOG.md
- e_metrobus/navigation/questions.py
- e_metrobus/navigation/tests/test_questions.py
- e_metrobus/navigation/urls.py
- e_metrobus/navigation/views.py
- e_metrobus/templates/navigation/answer.html
> Answered questions can be re-seen after clicking on finished category

- e_metrobus/navigation/chart.py
- e_metrobus/static/sass/_comparison.scss
- e_metrobus/templates/navigation/comparison.html
- e_metrobus/templates/navigation/environment.html
> Chart co2 info

- e_metrobus/templates/navigation/question.html
> Multiple choice answer button not greyed out without choice

- e_metrobus/navigation/constants.py
- e_metrobus/navigation/utils.py
- e_metrobus/static/sass/_comparison.scss
- e_metrobus/templates/navigation/answer.html
- e_metrobus/templates/questions/ich/footprint.html
- e_metrobus/templates/questions/politik/neutral.html
- e_metrobus/templates/questions/politik/schedule.html
- e_metrobus/templates/questions/umwelt/windturbines.html
- e_metrobus/templates/widgets/info_table.html
> Added sources and corrected some values

- CHANGELOG.md
- e_metrobus/navigation/constants.py
- e_metrobus/navigation/stations.py
- e_metrobus/navigation/views.py
- e_metrobus/static/sass/_environment.scss
- e_metrobus/templates/navigation/environment.html
> Fleet distance is calculated from project start

- CHANGELOG.md
- e_metrobus/__init__.py
- e_metrobus/templates/navigation/environment.html
- blocktrans error on environment page
> Fixed blocktrans error on environment page

- e_metrobus/navigation/chart.py
> Added "per person" to chart titles

- e_metrobus/templates/base.html
> Added container to clipboard to fix modal clipboard error

- e_metrobus/static/sass/_question.scss
> fix btn overlapping multiple choice answers

- e_metrobus/navigation/urls.py
- e_metrobus/navigation/views.py
> Refactored desktop page into class view including feedback mixin

- e_metrobus/static/sass/_comparison.scss
@henhuy I need to test in on a smartphone to see if it works properly now. But I think it should be good.
fix #504
> add extra bottom padding to table source

- e_metrobus/templates/navigation/comparison.html
- locale/en/LC_MESSAGES/django.po
> Fixed CO2 page title

- CHANGELOG.md
- e_metrobus/templates/includes/desktop.html
- e_metrobus/templates/navigation/summary.html
> Slim summary page

- locale/en/LC_MESSAGES/django.po
> Fixed twice answer in category "me"

- CHANGELOG.md
- e_metrobus/templates/includes/desktop.html
- e_metrobus/templates/navigation/display_route.html
- locale/en/LC_MESSAGES/django.po
Recreated translation file.
Following lines in [django.po file](https://github.com/rl-institut/E_Metrobus/blob/new_lp_translation/locale/en/LC_MESSAGES/django.po) need updates:
- 244
- 246
- 268
- 280
- 288
- 553
- 557
- 565
- 569
- 573
- 577
- 662
- 666
- 674
- 680
- 684
> New lp translation
